sudo: false
language: node_js

node_js:
  - "12"
  - node

script:
  - npm audit
  - if [[ ${TRAVIS_NODE_VERSION:0:2} == "12" ]]; then npm run coveralls; else npm test; fi

deploy:
  provider: npm
  email: ${NPM_USER}
  api_key: ${NPM_KEY}
  on:
    tags: true